services:
  telegrambot:
    container_name: BullAndCowsBot
    image: goodgateway/bcgamebot:latest
    depends_on: 
      - redis
    ports:
      - 1337:4562
    environment:
      - Redis__Url=redis:6379
      - ASPNETCORE_URLS=http://*:4562
    env_file:
      - config.env
  
  redis:
    container_name: Redis  
    image: redis:7.2
    ports:
      - 6379:6379